### ISSUE TITLE
能否增加对ssd后处理的demo代码？

### ISSUE THREAD

**Issue by kame-lqm** [yangfei963158659/nnie#11]
如题，如果增加对ssd的支持，这个框架会通用很多。我之前一直在用yolov3，速度还是有些慢，要是能用这个框架去推理ssd，那就perfect了。

**Comment by yangfei963158659** [comment]
yolov3有很多改进版本，速度和效果都很好。SSD感觉要out了

**Comment by kame-lqm** [comment]
> yolov3有很多改进版本，速度和效果都很好。SSD感觉要out了

了解，谢谢了。
