### ISSUE TITLE
能加联系方式交流吗

### ISSUE THREAD

**Issue by lqian** [yangfei963158659/nnie#14]
该死的海思官方nnie-samples，写的真是是没法形容，读取来，那叫一个疼苦，一个功能，封装了五六层，还不支持c++，工使用起来非常蹩脚。
最近利用海思的nnie原生API编写一个c++的demo，调用nnie原生API遇到了一些困惑和问题，能否和UP主进行一些交流。

**Comment by yangfei963158659** [comment]
可以。加我qq1540823178

**Comment by lqian** [comment]
> 
> 
> 可以。加我qq1540823178

加qq验证问题通不过，大神可以加我的qq33295203

**Comment by yangfei963158659** [comment]
我把验证信息取消了。你再加一下吧
